services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    restart: always

  server:
    build: .
    container_name: server
    ports:
      - 3000:3000
    links:
      - mongodb
    depends_on:
      - mongodb
    restart: always